### ISSUE TITLE
NSMgr leaks memory somewhere (probably in `grpcfd`)

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/cmd-nsmgr#375]
## Current Behavior
NSMgr leaks memory somewhere (probably in `grpcfd`) after long time working.
![image](https://user-images.githubusercontent.com/20160689/134500747-4a759de1-d65d-4a79-bd06-f2c9f1509d9d.png)
[nsmgr-8g8qn.pb.gz](https://github.com/networkservicemesh/cmd-nsmgr/files/7217272/nsmgr-8g8qn.pb.gz)

## Steps to Reproduce

1. Patch NSMgr with the following lines in `main.go`:
```go
import _ "net/http/pprof"
```
```go
go func() {
	_ = http.ListenAndServe("127.0.0.1:8080", nil)
}()
```
2. Run some example for a long time (12+ hours).
3. Collect heap profile with `go tools pprof`.

**Comment by Bolodya1997** [comment]
Tried to run NSM without any `grpcfd` either in networkservice or in registry chains. Almost no leaks for 3 days running setup.
[nsmgr-b6r9b.pb.gz](https://github.com/networkservicemesh/cmd-nsmgr/files/7235465/nsmgr-b6r9b.pb.gz)

In `inuse_objects` sample I can see registry `server.Find` leaks in spanlogger, there is already an issue for this - https://github.com/networkservicemesh/sdk/issues/1085.

In `inuse_space` sample there is a possible leak in gRPC `transport.NewBufWriter` (~1Mb), but there are only 17 objects, so it can be a normal behavior, needs to be further monitored.

**Comment by edwarnicke** [comment]
@Bolodya1997 grpcfd *should* be cleaning up after open file descriptors on connection close: https://github.com/edwarnicke/grpcfd/blob/aa90c1562fb36d3f274db049354d6a1e76fd325a/connwrap.go#L102-L122

**Comment by edwarnicke** [comment]
@Bolodya1997 in recvfd we are caching files and closing them when the client Connection closes: https://github.com/networkservicemesh/sdk/blob/204761283a51aa10efcf3d994c36c74b50355e26/pkg/networkservice/common/mechanisms/recvfd/client.go#L88-L94

But we appear to be neglecting to do so on the server side:

https://github.com/networkservicemesh/sdk/blob/204761283a51aa10efcf3d994c36c74b50355e26/pkg/networkservice/common/mechanisms/recvfd/server.go#L80-L109

In principle on the Server side once https://github.com/networkservicemesh/sdk/blob/204761283a51aa10efcf3d994c36c74b50355e26/pkg/networkservice/common/mechanisms/recvfd/server.go#L92 happens the files should eventually get closed due to finalization by the garbage collector... but explicit is better than implicit.

**Comment by Bolodya1997** [comment]
@edwarnicke 
There was an issue with finalizer, fixed it - https://github.com/edwarnicke/grpcfd/pull/19.

**Comment by edwarnicke** [comment]
@Bolodya1997 And released in https://github.com/edwarnicke/grpcfd/releases/tag/v0.1.1 :)  Many thanks :)
